/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesIdRouteImport } from './routes/series.$id'
import { Route as ReadSeriesIdEpisodePartRouteImport } from './routes/read.$seriesId.$episode.$part'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIdRoute = SeriesIdRouteImport.update({
  id: '/series/$id',
  path: '/series/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadSeriesIdEpisodePartRoute = ReadSeriesIdEpisodePartRouteImport.update({
  id: '/read/$seriesId/$episode/$part',
  path: '/read/$seriesId/$episode/$part',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/series/$id': typeof SeriesIdRoute
  '/read/$seriesId/$episode/$part': typeof ReadSeriesIdEpisodePartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/series/$id': typeof SeriesIdRoute
  '/read/$seriesId/$episode/$part': typeof ReadSeriesIdEpisodePartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/series/$id': typeof SeriesIdRoute
  '/read/$seriesId/$episode/$part': typeof ReadSeriesIdEpisodePartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/profile'
    | '/series/$id'
    | '/read/$seriesId/$episode/$part'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/profile'
    | '/series/$id'
    | '/read/$seriesId/$episode/$part'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/profile'
    | '/series/$id'
    | '/read/$seriesId/$episode/$part'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  ProfileRoute: typeof ProfileRoute
  SeriesIdRoute: typeof SeriesIdRoute
  ReadSeriesIdEpisodePartRoute: typeof ReadSeriesIdEpisodePartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$id': {
      id: '/series/$id'
      path: '/series/$id'
      fullPath: '/series/$id'
      preLoaderRoute: typeof SeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$seriesId/$episode/$part': {
      id: '/read/$seriesId/$episode/$part'
      path: '/read/$seriesId/$episode/$part'
      fullPath: '/read/$seriesId/$episode/$part'
      preLoaderRoute: typeof ReadSeriesIdEpisodePartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  ProfileRoute: ProfileRoute,
  SeriesIdRoute: SeriesIdRoute,
  ReadSeriesIdEpisodePartRoute: ReadSeriesIdEpisodePartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
